### ISSUE TITLE
profileNamingIsAvail obsolete?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wredProfile#2]
I assume that _profileNamingIsAvail_ refers to the _profileName_ attribute which seems to be the object key:

> partOfObjectKey: 1

Doesn't this mean that _profileName_ is mandatory and _profileNamingIsAvail_ obsolete?

**Comment by openBackhaul** [comment]
profileNamingIsAvail has been removed with WredProfile_1.0.0-tsp.190530.1310
Many thanks for commenting.
