### ISSUE TITLE
Uuid -> Leafref at Notifications

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wredProfile#6]
All *Notification::objectIdRef attributes will become _objectIdRef attributes generated from shared associations to LTP class in UML. This applies on all notifications.

All *notification::object-id-ref leaf will become leafref to LTP.

Only object-deletion-notification::object-id-ref : leafref will be "require-instance false;"

**Comment by PrathibaJee** [comment]
**(copied the comment content from openBackhaul/vlanInterface/issues /7 )**

All object-id-ref have been made require-instance false, because there was no way in Papyrus to make the UML2YANG tool to not add this statement.
No impact on the end2end functionality is expected from that.

**Comment by openBackhaul** [comment]
Solved with WredProfile_1.0.0-tsp.220330.1950.
